# Generated by Django 3.1.3 on 2020-11-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distant.assignment_dates', verbose_name='Дата задания'),
        ),
    ]
